local builtin = require('telescope.builtin')
local vim = vim
vim.keymap.set('n', 'ff', builtin.find_files, {})
vim.keymap.set('n', 'fw', builtin.live_grep, {})
vim.keymap.set('n', 'fb', builtin.buffers, {})
vim.keymap.set('n', 'fh', builtin.help_tags, {})
vim.keymap.set('n', '<C-n>', ":NvimTreeToggle<CR>", {})
vim.keymap.set('n', '<C-h>', "<C-w>h", {})
vim.keymap.set('n', '<C-l>', "<C-w>l", {})
vim.keymap.set('n', '<C-j>', "<C-w>j", {})
vim.keymap.set('n', '<C-k>', "<C-w>k", {})
vim.keymap.set('n', 'q', ":q<CR>", {})
vim.keymap.set('i', '<C-s>', "<ESC>:w<CR>", {})
vim.keymap.set('n', '<C-s>', "<ESC>:w<CR>", {})
vim.keymap.set('n', '<leader>f', ":lua vim.lsp.buf.format()<CR>", {})
vim.keymap.set('n', '<F5>', "<Esc><Cmd>ToggleTerm direction=float<CR>", {})
vim.keymap.set('t', '<F5>', "<C-\\><C-n><Esc><Cmd>ToggleTerm direction=float<CR>", {})


vim.keymap.set('n', 'gd', ":Lspsaga peek_definition<CR>", {})
vim.keymap.set('n', 'gD', ":lua vim.lsp.buf.definition()<CR>", {})
vim.keymap.set('n', 'gh', ":Lspsaga lsp_finder<CR>", {})
vim.keymap.set('n', '/', ":SearchBoxIncSearch<CR>", {})
vim.keymap.set('n', ':', "<cmd>FineCmdline<CR>", {})

